### ISSUE TITLE
Start/Restart Custom Dynamic Playlist via http request

### ISSUE THREAD

**Issue by the-other-martin** [AF-1/lms-dynamicplaylists#10]
I'm using the following http request to start one of my Custom Dynamic Playlists "03 Lieblingstitel":
`http://IP:9000/plugins/DynamicPlaylists4/dynamicplaylist_list.html?p0=dynamicplaylist&p1=playlist&p2=play&p3=dplusercustom_03%20lieblingstitel_new&player=xxxxxxxxxxxxxxxx`

When I use this request the first time, the DPL starts playing as expected.

When the DPL is paused or player is switched off (same DPL is still selected) and same http request is sent, nothing happens.
I would have expected to start the Custom Dynamic Playlist again (or at least continue to play same DPL).

background: I'd like to start DPL via simple iPhone Automation for scanning NFC tag and send http request (which works for the initial scan, but doesn't work for further scans)

Could you please have a look on this issue,
Martin

**Comment by AF-1** [comment]
If you use _dynamicplaylist playlist **play**_ for the _same_ dynamic playlist on the same player, DPL will do nothing because as far as it is concerned this dynamic playlist is already active. In this case _active_ means that DPL knows there's a dynamic playlist it should use to retrieve tracks for this player, if necessary.

I see 2 options:

- use _dynamicplaylist playlist **continue**_ if there's already an active dynamic playlist for a player you want to resume. You could do a query using _dynamicplaylist isactive_ to check if a client/player aleady has an active dynamic playlist. It's client-specific.

- Or much more simple and effective: just use an ordinary LMS _play_ or _pause_ command to resume playback on your player. If there's an active dynamic playlist on this player, DPL knows this and will use it to add tracks. No need to use a DPL command.

**Comment by the-other-martin** [comment]
Thanks for the super fast response!

I just have checked the standard behaviour of playlists with one example to play all "BTS" tracks:
`http://IP:9000/status.html?p0=playlist&p1=loadalbum&p2=*&p3=BTS&p4=*&player=xxxxxxxxxxxx`

If this http request is sent again, the playlist is retrieved and started again. Wouldn't it make sense to have same behaviour with DPLs?

**Comment by AF-1** [comment]
So you want the _dynamicplaylist playlist **play**_ command to **clear** the client playlist first and **re**start the same dynamic playlist (discarding all information about which tracks of this playlist have been played so far) and 
NOT resume playback / **continue** the current dynamic playlist?

I'll take a closer look.

**Comment by the-other-martin** [comment]
Yes, exactly as the LMS standard playlist behaviour. 
Thanks for your perfect support!

**Comment by AF-1** [comment]
Version 4.1.**2** should allow you to use the _play_ command to **restart** the currently active dynamic playlist. 
Please confirm before closing. Thank you.

**Comment by the-other-martin** [comment]
great, works perfectly fine! many thanks!
